<?php
$LOCAL_LANG = array(
  'default' => array(
    'sheet_sDEF'                                => 'Calendar',
    'sheet_sDEF.tutorial'                       => 'Tutorial',
    'sheet_sDEF.tutorial.0'                     => 'http://typo3.org/extensions/repository/view/browser_tut_calendar_en/current/',
    'sheet_sDEF.checklist'                      => 'Checklist',
    'sheet_sDEF.checklist.0'                    => 'Yes, I have included the static templates "Browser" and "+Browser Calendar"!',
    'sheet_sDEF.template'                       => 'Template',
    'sheet_sDEF.templatePath'                   => 'Own HTML file',
    'sheet_sDEF.initialView'                    => 'Initial View',
    'sheet_sDEF.initialView.year'               => 'Year',
    'sheet_sDEF.initialView.month'              => 'Month',
    'sheet_sDEF.initialView.week'               => 'Week',
    'sheet_sDEF.initialView.day'                => 'Day',
    'sheet_sDEF.configured'                     => 'Configuration',
    'sheet_sDEF.configured.default'             => 'Default',
    'sheet_sDEF.configured.adapted'             => 'Adapted',
    'sheet_sDEF.singlePid'                      => 'Configuration: Page with Single View (empty value: this page)',

    'sheet_year'                                => 'Years',
    'sheet_year.configuration'                  => 'Area of Years',
    'sheet_year.configuration.relative'         => 'Relative',
    'sheet_year.configuration.absolute'         => 'Absolute',
    'sheet_year.relativeFrom'                   => 'Relative from',
    'sheet_year.relativeTo'                     => 'Relative to',
    'sheet_year.absoluteFrom'                   => 'Absolute from',
    'sheet_year.absoluteTo'                     => 'Absolute to',
  ),
  'de' => array(
    
    'sheet_sDEF'                                => 'Kalender',
    'sheet_sDEF.tutorial'                       => 'Tutorial',
    'sheet_sDEF.tutorial.0'                     => 'http://typo3.org/extensions/repository/view/browser_tut_calendar_en/current/',
    'sheet_sDEF.checklist'                      => 'Checkliste',
    'sheet_sDEF.checklist.0'                    => 'Ja, ich habe die Statischen Templates "Browser" und "+Browser Kalender" eingebunden!',
    'sheet_sDEF.template'                       => 'Template',
    'sheet_sDEF.templatePath'                   => 'Eigene HTML-Datei',
    'sheet_sDEF.initialView'                    => 'Start Ansicht',
    'sheet_sDEF.initialView.year'               => 'Jahr',
    'sheet_sDEF.initialView.month'              => 'Monat',
    'sheet_sDEF.initialView.week'               => 'Woche',
    'sheet_sDEF.initialView.day'                => 'Tag',
    'sheet_sDEF.configured'                     => 'Konfiguration',
    'sheet_sDEF.configured.default'             => 'Standard',
    'sheet_sDEF.configured.adapted'             => 'Angepasst',
    'sheet_sDEF.singlePid'                      => 'Konfiguration: Seite mit Einzelansicht (leer: diese Seite)',

    'sheet_year'                                => 'Jahre',
    'sheet_year.configuration'                  => 'Bereich der Jahre',
    'sheet_year.configuration.relative'         => 'Relativ',
    'sheet_year.configuration.absolute'         => 'Absolut',
    'sheet_year.relativeFrom'                   => 'Relativ von',
    'sheet_year.relativeTo'                     => 'Relativ bis',
    'sheet_year.absoluteFrom'                   => 'Absolut von',
    'sheet_year.absoluteTo'                     => 'Absolut bis',
  ),
);
?>